In [124]:
import numpy as np
import pandas as pd
import random as rnd

In [2]:
def fitness(theta, no_result, examples):
    nac = 0
    nic = 0
    ta = 0
    ti = 0
    
    # Cria um array contendo 100 indices que serão visitados na matriz original, para testar a qualidade deste cromossomo
    indexes = np.random.randint(no_result.shape[0], size=100)

    for i in indexes:
        cr = no_result.iloc[i] * theta
        cr_sum = cr.sum()
        if ((cr_sum > 0) and (examples.iloc[i].Resultado == "A")):
            nac += 1
        elif ((cr_sum < 0) and (examples.iloc[i].Resultado == "I")):
            nic += 1
            
        if (examples.iloc[i].Resultado == "A"):
            ta += 1
        else:
            ti += 1

    return (nac * nic) / (ta * ti)

In [33]:
def gen_cr(features, amount=1):
    return np.random.uniform(low=-1., high=1., size=(amount, features))

In [41]:
def crossover(first, second, amount=3):
    parent_size = first.size
    offsprings = []

    for i in range(amount):
        random_index = np.random.randint(parent_size, size=1)[0]
        first_part = first[:random_index]
        second_part = second[random_index:]
        offspring = np.append(first_part, second_part)
        offsprings.append(offspring)
    
    return np.array(offsprings)

In [5]:
def mutate(cr):
    random_cr_index = np.random.randint(cr.size, size=1)[0]
    cr[random_cr_index] = np.random.uniform(low=-1., high=1., size=no_result.shape[1])[0]
    return cr

In [104]:
def max2(data):
    copied = data.copy()
    sorted_data = np.sort(copied)
    return (sorted_data[-1], sorted_data[-2])

In [110]:
def min2(data):
    copied = data.copy()
    sorted_data = np.sort(copied)
    return (sorted_data[0], sorted_data[1])

In [6]:
examples = pd.read_csv("data/creditus-data.csv", sep=";", index_col=0, header=0)

In [7]:
examples.head(5)

X11  X12  X21  X22  X31  X32  X41  X42  X51  X52  X61  X62  X71  X72  \
Y001    1    0    0    1    1    0    0    1    0    1    1    0    0    1   
Y002    0    1    0    1    1    0    0    1    0    1    1    0    0    1   
Y003    1    0    1    0    0    1    1    0    1    0    0    1    1    0   
Y004    1    0    1    0    0    1    1    0    1    0    0    1    1    0   
Y005    0    1    0    1    1    0    0    1    0    1    1    0    0    1   

      X81  X82  X91  X92 Resultado  
Y001    1    0    1    0         A  
Y002    1    0    1    0         A  
Y003    0    1    0    1         I  
Y004    0    1    0    1         I  
Y005    1    0    1    0         A

In [8]:
# Variáveis do problema, conforme apostila
ta = examples[examples.Resultado == 'A'].shape[0]  # número total de adimplentes 
ti = examples[examples.Resultado == 'I'].shape[0]  # número total de inadimplentes

In [9]:
no_result = examples.drop(["Resultado"], axis = 1)

In [10]:
no_result.head(5)

X11  X12  X21  X22  X31  X32  X41  X42  X51  X52  X61  X62  X71  X72  \
Y001    1    0    0    1    1    0    0    1    0    1    1    0    0    1   
Y002    0    1    0    1    1    0    0    1    0    1    1    0    0    1   
Y003    1    0    1    0    0    1    1    0    1    0    0    1    1    0   
Y004    1    0    1    0    0    1    1    0    1    0    0    1    1    0   
Y005    0    1    0    1    1    0    0    1    0    1    1    0    0    1   

      X81  X82  X91  X92  
Y001    1    0    1    0  
Y002    1    0    1    0  
Y003    0    1    0    1  
Y004    0    1    0    1  
Y005    1    0    1    0

In [11]:
# Cria uma matriz de tamanho equivalente a matriz no_result
random_values = np.random.uniform(low=-1., high=1., size=no_result.shape)

In [12]:
random_values

array([[-0.79246879, -0.08690969, -0.66109876, ..., -0.80630245,
         0.17371935,  0.92266564],
       [ 0.45959621,  0.00556263,  0.17305229, ...,  0.45149767,
         0.44245359,  0.02065674],
       [-0.88309193, -0.27866566, -0.24321182, ..., -0.18532476,
        -0.12889785, -0.19641921],
       ...,
       [-0.01113689, -0.46624517, -0.77276606, ..., -0.09733311,
        -0.48108768,  0.84984458],
       [ 0.64841945, -0.83140768,  0.79550414, ..., -0.75955208,
         0.70963087, -0.34736416],
       [ 0.29150978, -0.64329762, -0.65402071, ...,  0.45850837,
        -0.20731019,  0.3700659 ]])

In [13]:
cr = no_result * random_values

In [14]:
cr.head(5)

X11       X12       X21       X22       X31       X32       X41  \
Y001 -0.792469 -0.000000 -0.000000  0.803222  0.740166  0.000000 -0.000000   
Y002  0.000000  0.005563  0.000000  0.892146  0.256371 -0.000000 -0.000000   
Y003 -0.883092 -0.000000 -0.243212 -0.000000  0.000000  0.727333  0.920057   
Y004  0.792947  0.000000  0.714261 -0.000000 -0.000000 -0.028885  0.449441   
Y005 -0.000000  0.335513  0.000000 -0.261356  0.598860 -0.000000 -0.000000   

           X42       X51       X52       X61       X62       X71       X72  \
Y001 -0.937999 -0.000000  0.417095 -0.979945 -0.000000  0.000000 -0.065821   
Y002 -0.189999  0.000000  0.825324 -0.087546 -0.000000  0.000000 -0.066459   
Y003  0.000000  0.191235 -0.000000 -0.000000 -0.405025 -0.125252  0.000000   
Y004  0.000000 -0.946584 -0.000000 -0.000000 -0.848495  0.815659  0.000000   
Y005 -0.518543  0.000000 -0.973796 -0.870914 -0.000000  0.000000  0.742737   

           X81       X82       X91       X92  
Y001  0.087170 -0.000000  0.173719  0.000000  
Y002  0.856303  0.000000  0.442454  0.000000  
Y003  0.000000 -0.185325 -0.000000 -0.196419  
Y004  0.000000  0.160465  0.000000  0.398296  
Y005 -0.734927  0.000000  0.081829  0.000000

In [15]:
cr_sum = cr.sum(axis=1)

In [16]:
cr_sum.head(5)

Y001   -0.554861
Y002    2.934155
Y003   -0.199701
Y004    1.507106
Y005   -1.600596
dtype: float64

In [17]:
pd.Series(examples.Resultado).head(5)

Y001    A
Y002    A
Y003    I
Y004    I
Y005    A
Name: Resultado, dtype: object

In [18]:
cr_sum.head(5)

Y001   -0.554861
Y002    2.934155
Y003   -0.199701
Y004    1.507106
Y005   -1.600596
dtype: float64

In [19]:
dict = {
    "summation": pd.Series(cr_sum),
    "label": pd.Series(examples.Resultado)
}

In [20]:
labeled_cr = pd.DataFrame(dict)

In [21]:
labeled_cr.head(5)

summation label
Y001  -0.554861     A
Y002   2.934155     A
Y003  -0.199701     I
Y004   1.507106     I
Y005  -1.600596     A

In [22]:
nac = labeled_cr[(labeled_cr.summation > 0) & (labeled_cr.label == "A")]
nic = labeled_cr[(labeled_cr.summation < 0) & (labeled_cr.label == "I")]

In [23]:
nac.head(5) # O cálculo do NAC e NIC ainda não fazem sentido...

summation label
Y002   2.934155     A
Y007   0.873443     A
Y012   1.460904     A
Y013   2.924234     A
Y015   0.087627     A

In [24]:
# Cria um array de tamanho equivalente à linha da matriz, parece mais conveniente que a abordagem anterior
random_theta = np.random.uniform(low=-1., high=1., size=no_result.shape[1])

In [25]:
fitness(random_theta, no_result, examples)

0.49759615384615385

In [26]:
cr_size = no_result.shape[1]
gen_cr(cr_size)

array([[-0.59038486],
       [ 0.27237952],
       [-0.41127318],
       [-0.48308662],
       [-0.25974844],
       [-0.84556357],
       [ 0.15298433],
       [-0.13699439],
       [ 0.48975905],
       [-0.59719941],
       [-0.41194907],
       [-0.44256144],
       [ 0.31637698],
       [-0.55056965],
       [ 0.85582588],
       [ 0.44504727],
       [ 0.10046597],
       [-0.02089267]])

In [27]:
crossover(gen_cr(cr_size), gen_cr(cr_size), 3)

array([[ 0.16748531,  0.40744378,  0.40567316,  0.53816096,  0.77859649,
         0.51366725,  0.1496155 , -0.9493547 , -0.45165378,  0.71647243,
         0.50162341,  0.7726995 ,  0.57354729,  0.12383533, -0.02373492,
        -0.04396867,  0.70547728,  0.42493993],
       [ 0.16748531,  0.40744378,  0.40567316,  0.53816096,  0.77859649,
         0.51366725,  0.1496155 , -0.9493547 , -0.45165378,  0.71647243,
         0.50162341,  0.7726995 ,  0.57354729, -0.54252488, -0.66262839,
        -0.02619696, -0.0783992 ,  0.42493993],
       [ 0.16748531,  0.40744378,  0.40567316,  0.53816096,  0.77859649,
        -0.48967858,  0.65187856,  0.34968272, -0.16353688, -0.99727864,
         0.34758623,  0.01745563, -0.15443481,  0.12383533, -0.02373492,
        -0.04396867,  0.70547728,  0.42493993]])

In [28]:
mutate(gen_cr(cr_size))

array([[-0.55331468],
       [-0.62676463],
       [ 0.18635536],
       [ 0.88636686],
       [-0.91702394],
       [-0.06456671],
       [-0.11420675],
       [-0.52179383],
       [ 0.30512454],
       [ 0.77218739],
       [-0.33760478],
       [-0.10741304],
       [ 0.04187682],
       [ 0.31107237],
       [ 0.82346082],
       [-0.36839674],
       [-0.52049656],
       [ 0.12544004]])

In [56]:
cr_database = gen_cr(no_result.shape[1], 6) # gera os 6 cromossomos

In [57]:
parent_indexes = np.random.randint(cr_database.shape[0], size=2)
parent_indexes

array([3, 2])

In [58]:
first = cr_database[parent_indexes[0]]
second = cr_database[parent_indexes[1]]
offspring1 = crossover(first, second)

In [72]:
offspring2 = offspring1.copy()
for i in range(len(offspring2)):
    offspring2[i] = mutate(offspring2[i])
offspring = np.concatenate((offspring1, offspring2))

[[ 0.38738386 -0.5035229  -0.43141642  0.18030899  0.96386627 -0.52083227
   0.30306998  0.43418123  0.2024884   0.77606584 -0.53613004 -0.72472368
  -0.10331059 -0.47455688  0.35019595 -0.45609653  0.3051136  -0.93514051]
 [ 0.38738386 -0.5035229  -0.43141642  0.18030899  0.96386627 -0.52083227
   0.30306998  0.43418123  0.2024884   0.77606584 -0.53613004 -0.72472368
  -0.69318665 -0.98165164  0.04383334 -0.45609653  0.3051136  -0.93514051]
 [ 0.38738386 -0.5035229  -0.43141642  0.18030899  0.96386627 -0.52083227
  -0.80038408  0.49226102  0.54804165  0.92320022  0.35411562 -0.68164935
  -0.10331059 -0.47455688  0.35019595 -0.45609653  0.3051136  -0.93514051]
 [ 0.38738386 -0.5035229  -0.43141642  0.18030899  0.96386627 -0.52083227
   0.30306998  0.43418123  0.2024884   0.77606584 -0.53613004 -0.72472368
  -0.10331059 -0.47455688  0.35019595  0.52441603  0.3051136  -0.93514051]
 [ 0.38738386 -0.5035229  -0.43141642  0.18030899  0.96386627 -0.52083227
   0.55325527  0.43418123  0.20248

In [78]:
db_fitness = [fitness(theta, no_result, examples) for theta in iter(cr_database)]

In [107]:
offspring_fitness = [fitness(theta, no_result, examples) for theta in iter(offspring)]

In [108]:
offspring_fitness

[0.3307151715584952,
 0.2167804094741068,
 0.30833333333333335,
 0.4384057971014493,
 0.376,
 0.2688]

In [112]:
max1, max2 = max2(offspring_fitness)

In [113]:
min1, min2 = min2(db_fitness)

In [114]:
print("antes")
print(cr_database)
cr_database[db_fitness.index(min1)] = offspring[offspring_fitness.index(max1)]
cr_database[db_fitness.index(min2)] = offspring[offspring_fitness.index(max2)]
print("depois")
print(cr_database)

antes
[[ 0.63428578 -0.2469513   0.19137826  0.66522184 -0.16358979 -0.20090695
  -0.84231704 -0.34406413 -0.35570383 -0.09092817  0.14320893  0.00217052
  -0.50126606  0.96170011 -0.21955565  0.48156012  0.40539212  0.37281646]
 [-0.68691878  0.28531932  0.2484147   0.01014519  0.53841165  0.00548801
  -0.19276649 -0.28410686  0.76940517  0.13194323 -0.99249141 -0.53526052
  -0.3084102   0.41702338 -0.4608769   0.67648999 -0.36575957  0.42195965]
 [ 0.72264322  0.88749292  0.93178459 -0.00388039  0.34394539 -0.21030285
  -0.80038408  0.49226102  0.54804165  0.92320022  0.35411562 -0.68164935
  -0.10331059 -0.47455688  0.35019595 -0.45609653  0.3051136  -0.93514051]
 [ 0.38738386 -0.5035229  -0.43141642  0.18030899  0.96386627 -0.52083227
   0.30306998  0.43418123  0.2024884   0.77606584 -0.53613004 -0.72472368
  -0.69318665 -0.98165164  0.04383334 -0.33448754  0.97715559  0.27575414]
 [-0.56736151 -0.61674629  0.87093702  0.21958304 -0.55553701  0.61338662
  -0.09078014  0.60537022  0

In [116]:
fit = [fitness(theta, no_result, examples) for theta in iter(cr_database)]

In [126]:
xx = np.array(fit).cumsum()

In [128]:
xx

array([0.45898359, 0.83842056, 1.17402875, 1.62806327, 1.68431327,
       2.15346912])

In [131]:
rnd.uniform(0, max(xx))

1.708241734190329