In [1]:
import numpy as np
import pandas as pd
import random as rnd

In [2]:
def fitness(theta, no_result, examples):
    nac = 0
    nic = 0
    ta = 0
    ti = 0
    
    # Cria um array contendo 100 indices que serão visitados na matriz original, para testar a qualidade deste cromossomo
    indexes = np.random.randint(no_result.shape[0], size=100)

    for i in indexes:
        cr = no_result.iloc[i] * theta
        cr_sum = cr.sum()
        if ((cr_sum > 0) and (examples.iloc[i].Resultado == "A")):
            nac += 1
        elif ((cr_sum < 0) and (examples.iloc[i].Resultado == "I")):
            nic += 1
            
        if (examples.iloc[i].Resultado == "A"):
            ta += 1
        else:
            ti += 1

    return (nac * nic) / (ta * ti)

In [3]:
def gen_cr(features, amount=1):
    if amount > 1:
        return np.random.uniform(low=-1., high=1., size=(amount, features))
    else:
        return np.random.uniform(low=-1., high=1., size=features)

In [4]:
def crossover(first, second, amount=3):
    parent_size = first.size
    offsprings = []

    for i in range(amount):
        random_index = np.random.randint(parent_size-1, size=1)[0]
        first_part = first[:random_index]
        second_part = second[random_index:]
        offspring = np.append(first_part, second_part)
        offsprings.append(offspring)
    
    return np.array(offsprings)

In [5]:
def mutate(cr):
    print(cr)
    random_cr_index = np.random.randint(cr.size-1, size=1)[0]
    print(random_cr_index)
    random_value = np.random.uniform(low=-1., high=1., size=no_result.shape[1])[0]
    print(random_value)
    cr[random_cr_index] = random_value
    return cr

In [6]:
def max2(data):
    copied = data.copy()
    sorted_data = np.sort(copied)
    return (sorted_data[-1], sorted_data[-2])

In [7]:
def min2(data):
    copied = data.copy()
    sorted_data = np.sort(copied)
    return (sorted_data[0], sorted_data[1])

In [ ]:
def wheel_of_chance(fitness_array):
    cumulative_sum = np.array(fitness_array).cumsum()
    return rnd.uniform(0, max(cumulative_sum))

In [8]:
examples = pd.read_csv("data/creditus-data.csv", sep=";", index_col=0, header=0)

In [9]:
examples.head(5)

X11  X12  X21  X22  X31  X32  X41  X42  X51  X52  X61  X62  X71  X72  \
Y001    1    0    0    1    1    0    0    1    0    1    1    0    0    1   
Y002    0    1    0    1    1    0    0    1    0    1    1    0    0    1   
Y003    1    0    1    0    0    1    1    0    1    0    0    1    1    0   
Y004    1    0    1    0    0    1    1    0    1    0    0    1    1    0   
Y005    0    1    0    1    1    0    0    1    0    1    1    0    0    1   

      X81  X82  X91  X92 Resultado  
Y001    1    0    1    0         A  
Y002    1    0    1    0         A  
Y003    0    1    0    1         I  
Y004    0    1    0    1         I  
Y005    1    0    1    0         A

In [10]:
# Variáveis do problema, conforme apostila
ta = examples[examples.Resultado == 'A'].shape[0]  # número total de adimplentes 
ti = examples[examples.Resultado == 'I'].shape[0]  # número total de inadimplentes

In [11]:
no_result = examples.drop(["Resultado"], axis = 1)

In [12]:
no_result.head(5)

X11  X12  X21  X22  X31  X32  X41  X42  X51  X52  X61  X62  X71  X72  \
Y001    1    0    0    1    1    0    0    1    0    1    1    0    0    1   
Y002    0    1    0    1    1    0    0    1    0    1    1    0    0    1   
Y003    1    0    1    0    0    1    1    0    1    0    0    1    1    0   
Y004    1    0    1    0    0    1    1    0    1    0    0    1    1    0   
Y005    0    1    0    1    1    0    0    1    0    1    1    0    0    1   

      X81  X82  X91  X92  
Y001    1    0    1    0  
Y002    1    0    1    0  
Y003    0    1    0    1  
Y004    0    1    0    1  
Y005    1    0    1    0

In [13]:
# Cria uma matriz de tamanho equivalente a matriz no_result
random_values = np.random.uniform(low=-1., high=1., size=no_result.shape)

In [14]:
random_values

array([[ 0.42117918, -0.77695305, -0.43188157, ..., -0.07289017,
         0.98085864,  0.89119282],
       [ 0.05447158, -0.87152144,  0.05648627, ...,  0.26524754,
         0.71903033, -0.55616413],
       [ 0.44185572,  0.52102227,  0.99100152, ..., -0.16072005,
         0.86936747,  0.84726153],
       ...,
       [-0.59373875,  0.43400906,  0.25291596, ..., -0.5629553 ,
         0.73304001, -0.24769141],
       [ 0.31493044,  0.34172218,  0.70801551, ...,  0.06564576,
         0.05365639,  0.92073804],
       [ 0.77740102, -0.4798296 ,  0.32868675, ..., -0.11901703,
        -0.5517381 ,  0.33921456]])

In [15]:
cr = no_result * random_values

In [16]:
cr.head(5)

X11       X12       X21       X22       X31       X32       X41  \
Y001  0.421179 -0.000000 -0.000000 -0.999008 -0.018838 -0.000000  0.000000   
Y002  0.000000 -0.871521  0.000000 -0.547924  0.303325  0.000000  0.000000   
Y003  0.441856  0.000000  0.991002  0.000000  0.000000 -0.854177  0.095530   
Y004  0.573596  0.000000 -0.629755 -0.000000 -0.000000 -0.615991  0.181362   
Y005  0.000000 -0.229499  0.000000 -0.151239 -0.504635 -0.000000 -0.000000   

           X42       X51       X52       X61       X62       X71       X72  \
Y001  0.480522  0.000000  0.757705  0.184648  0.000000 -0.000000  0.484061   
Y002 -0.546246  0.000000  0.214729 -0.505961 -0.000000 -0.000000  0.480739   
Y003 -0.000000  0.594029 -0.000000 -0.000000 -0.557569  0.864736  0.000000   
Y004 -0.000000  0.350991 -0.000000  0.000000 -0.265070 -0.598619  0.000000   
Y005 -0.792225 -0.000000  0.582504 -0.977086 -0.000000  0.000000 -0.109519   

           X81       X82       X91       X92  
Y001 -0.397233 -0.000000  0.980859  0.000000  
Y002  0.093073  0.000000  0.719030 -0.000000  
Y003 -0.000000 -0.160720  0.000000  0.847262  
Y004  0.000000  0.803389  0.000000 -0.391425  
Y005 -0.988631 -0.000000  0.581495 -0.000000

In [17]:
cr_sum = cr.sum(axis=1)

In [18]:
cr_sum.head(5)

Y001    1.893895
Y002   -0.660757
Y003    2.261949
Y004   -0.591522
Y005   -2.588835
dtype: float64

In [19]:
pd.Series(examples.Resultado).head(5)

Y001    A
Y002    A
Y003    I
Y004    I
Y005    A
Name: Resultado, dtype: object

In [20]:
cr_sum.head(5)

Y001    1.893895
Y002   -0.660757
Y003    2.261949
Y004   -0.591522
Y005   -2.588835
dtype: float64

In [21]:
dict = {
    "summation": pd.Series(cr_sum),
    "label": pd.Series(examples.Resultado)
}

In [22]:
labeled_cr = pd.DataFrame(dict)

In [23]:
labeled_cr.head(5)

summation label
Y001   1.893895     A
Y002  -0.660757     A
Y003   2.261949     I
Y004  -0.591522     I
Y005  -2.588835     A

In [24]:
nac = labeled_cr[(labeled_cr.summation > 0) & (labeled_cr.label == "A")]
nic = labeled_cr[(labeled_cr.summation < 0) & (labeled_cr.label == "I")]

In [25]:
nac.head(5) # O cálculo do NAC e NIC ainda não fazem sentido...

summation label
Y001   1.893895     A
Y006   0.254706     A
Y013   1.436485     A
Y023   2.568091     A
Y025   0.398419     A

In [26]:
# Cria um array de tamanho equivalente à linha da matriz, parece mais conveniente que a abordagem anterior
random_theta = np.random.uniform(low=-1., high=1., size=no_result.shape[1])

In [27]:
fitness(random_theta, no_result, examples)

0.515625

In [28]:
cr_size = no_result.shape[1]
gen_cr(cr_size)

array([-0.84537429,  0.74167581,  0.71868499, -0.74228115, -0.21136563,
        0.50659771,  0.89209214,  0.03931989,  0.66648076,  0.70420745,
        0.58505079,  0.19477452, -0.15796128,  0.74382386,  0.19977844,
       -0.95189424, -0.29000941, -0.7011089 ])

In [29]:
crossover(gen_cr(cr_size), gen_cr(cr_size), 3)

array([[-0.67665573,  0.22323925,  0.32843155, -0.18055314, -0.25309979,
        -0.17689205,  0.03770006, -0.86837803, -0.66973754,  0.4473252 ,
         0.67257227, -0.20261922, -0.36675819, -0.18825205, -0.93340672,
        -0.81619935,  0.67836332, -0.26311613],
       [-0.67665573,  0.22323925,  0.32843155, -0.18055314, -0.25309979,
        -0.17689205,  0.48914266,  0.83538954,  0.44412545,  0.2412712 ,
        -0.47141996,  0.74958172,  0.3838556 , -0.18825205, -0.93340672,
        -0.81619935,  0.67836332, -0.26311613],
       [-0.67665573,  0.22323925,  0.32843155, -0.18055314, -0.25309979,
        -0.17689205,  0.48914266,  0.83538954,  0.44412545,  0.2412712 ,
         0.67257227, -0.20261922, -0.36675819, -0.18825205, -0.93340672,
        -0.81619935,  0.67836332, -0.26311613]])

In [30]:
mutate(gen_cr(cr_size))

[-0.53403975 -0.35191211 -0.01624314  0.31355631 -0.02277363 -0.24235665
 -0.84687327 -0.01106554 -0.53278644 -0.66319712  0.70033324 -0.21482325
 -0.69834629 -0.73103046  0.60481386 -0.12879348 -0.66923058  0.81601777]
14
-0.1975357451801616


array([-0.53403975, -0.35191211, -0.01624314,  0.31355631, -0.02277363,
       -0.24235665, -0.84687327, -0.01106554, -0.53278644, -0.66319712,
        0.70033324, -0.21482325, -0.69834629, -0.73103046, -0.19753575,
       -0.12879348, -0.66923058,  0.81601777])

In [31]:
cr_database = gen_cr(no_result.shape[1], 6) # gera os 6 cromossomos

In [32]:
parent_indexes = np.random.randint(cr_database.shape[0], size=2)
parent_indexes

array([2, 5])

In [33]:
first = cr_database[parent_indexes[0]]
second = cr_database[parent_indexes[1]]
offspring1 = crossover(first, second)

In [34]:
offspring2 = offspring1.copy()
for i in range(len(offspring2)):
    offspring2[i] = mutate(offspring2[i])
offspring = np.concatenate((offspring1, offspring2))

[-0.96538756 -0.22522742  0.28388056 -0.65819697  0.63996246 -0.96956592
 -0.54252319 -0.38666203 -0.3078905  -0.85264061 -0.98221943  0.36317047
 -0.31877456  0.04338957 -0.58481671 -0.04402483  0.46892639 -0.17406682]
14
-0.27811787698000856
[-0.96538756 -0.22522742  0.28388056 -0.65819697  0.63996246 -0.96956592
 -0.54252319 -0.38666203 -0.3078905  -0.85264061 -0.9574135   0.36317047
 -0.31877456  0.04338957 -0.58481671 -0.04402483  0.46892639 -0.17406682]
11
-0.29344371240515077
[-0.96538756 -0.22522742  0.28388056 -0.65819697  0.15650051  0.68152174
  0.15455461  0.81387424 -0.46676346  0.33929855 -0.9574135   0.36317047
 -0.31877456  0.04338957 -0.58481671 -0.04402483  0.46892639 -0.17406682]
9
0.878563416460324


In [35]:
db_fitness = [fitness(theta, no_result, examples) for theta in iter(cr_database)]

In [36]:
offspring_fitness = [fitness(theta, no_result, examples) for theta in iter(offspring)]

In [37]:
offspring_fitness

[0.0,
 0.0,
 0.21827201322860687,
 0.02040816326530612,
 0.06818181818181818,
 0.28125]

In [38]:
max1, max2 = max2(offspring_fitness)

In [39]:
min1, min2 = min2(db_fitness)

In [40]:
print("antes")
print(cr_database)
cr_database[db_fitness.index(min1)] = offspring[offspring_fitness.index(max1)]
cr_database[db_fitness.index(min2)] = offspring[offspring_fitness.index(max2)]
print("depois")
print(cr_database)

antes
[[-7.77242262e-04  2.20439325e-02  7.07327093e-01 -9.45117065e-01
   9.03008281e-01 -4.99028157e-01  3.06905796e-01  3.84146464e-01
  -3.87357398e-01 -5.80457917e-01 -8.82916671e-01  2.40219360e-01
  -3.86581658e-01 -1.47902287e-01  6.83174013e-01  7.10179202e-02
   8.39378071e-01  9.23763265e-01]
 [-7.36452059e-01  6.83247774e-01 -5.99516901e-02 -1.93787016e-01
  -2.18222214e-01  6.01533339e-01  2.65214768e-02  6.17451716e-01
   9.04898877e-01  4.12422121e-01 -1.48757667e-01 -2.42054277e-01
  -1.54939864e-01 -8.33493410e-01  3.71778596e-01 -7.08657110e-01
  -8.95343227e-01  7.25863695e-01]
 [-9.65387559e-01 -2.25227420e-01  2.83880562e-01 -6.58196965e-01
   6.39962458e-01 -9.69565918e-01 -5.42523189e-01 -3.86662026e-01
  -3.07890497e-01 -8.52640610e-01 -9.82219435e-01  7.74104371e-01
   6.52589693e-01 -1.64714863e-01 -6.27508728e-01  5.22386117e-01
  -1.66667673e-01  9.92509521e-01]
 [-7.93620219e-01 -6.42472584e-01  9.70366829e-01  8.80848020e-01
   9.70019206e-01 -4.38008368e-

In [41]:
fit = [fitness(theta, no_result, examples) for theta in iter(cr_database)]

array([0.17708333, 0.30608974, 0.35897436, 0.90212972, 1.1044581 ,
       1.39536719])

1.2113941073639791